@baseUrl = http://localhost:3000
@authToken = ad3b1365c5336fe28ccf0db4763f041da6b36227c2e18c89

### 1. Проверка здоровья (Health Check)
# Публичный доступ (без ключа)
GET {{baseUrl}}/api/health

###

### 2. Список моделей (Protected)
GET {{baseUrl}}/api/models
x-api-key: {{authToken}}

###

### 3. Стандартный чат (Chat History)
POST {{baseUrl}}/api/chat
Content-Type: application/json
x-api-key: {{authToken}}

{
    "messages": [
        { "role": "system", "content": "Ты - опытный JS разработчик." },
        { "role": "user", "content": "Как отсортировать массив объектов?" }
    ],
    "model": "gemini-2.5-flash-lite"
}

###

### 4. Тест ошибки (Нет ключа)
POST {{baseUrl}}/api/chat
Content-Type: application/json

{
    "messages": [{ "role": "user", "content": "Hack access" }]
}

###

### 5. Потоковый чат (Streaming SSE)
POST {{baseUrl}}/api/chat/stream
Content-Type: application/json
Accept: text/event-stream
x-api-key: {{authToken}}

{
    "messages": [
        { "role": "user", "content": "Напиши хокку про дождь." }
    ],
    "model": "gemini-2.5-flash"
}
